config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_blocked', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'  
  root 'breweries#index'
  resources :places, only:[:index, :show]
  post 'places', to:'places#search'
end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings

  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 30 }
  validates :password, length: { minimum: 4 }   
  validates :password, format: { with: /([A-Z].*\d)|(\d.*[A-Z].*)/,
              message: "should contain one number and one capital letter" }   

  def favorite_beer
    return nil if ratings.empty?   
    ratings.order(score: :desc).limit(1).first.beer            
  end              

  def favorite_brewery
    return nil if ratings.empty? 
    
    ratings_of_breweries = ratings.group_by { |r| r.beer.brewery }
    averages_of_breweries = []
    ratings_of_breweries.each do |brewery, ratings|
      averages_of_breweries << {
        brewery: brewery,
        rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end  
    averages_of_breweries.sort_by{ |b| -b[:rating] }.first[:brewery]
  end  

  def favorite_style
    return nil if ratings.empty? 
    
    ratings_of_styles = ratings.group_by { |r| r.beer.style }
    averages_of_styles = []
    ratings_of_styles.each do |style, ratings|
      averages_of_styles << {
        style: style,
        rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end  
    averages_of_styles.sort_by{ |b| -b[:rating] }.first[:style]
  end   

  def is_member_of?(beer_club)
    beer_clubs.include? beer_club
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user==current_user and @user.update(user_params) 
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if @user==current_user 
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_blocked
    if current_user.admin
    user = User.find(params[:id])
    user.update_attribute :blocked, (not user.blocked)

    new_status = user.blocked? ? "frozen": "reactivated"

    redirect_to :back, notice: "Account #{new_status}"
    else
    redirect_to :back, notice: "You need signin with admin account"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>  
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username%></h1>

<%= render 'form' %>

<%= link_to 'back', @user %> 

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th> rated beers </th>
    <th> total ratings </th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if user.frozen? %>
              <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @user.username %></h2>

<%if @user.blocked%>
  <p class="bg-info"> account frozen </>
<%end%>

<p>Has made <%= @user.ratings.count %> ratings</p>

<% if @user.beer_clubs.any? %>

  <p>member of
  <% @user.beer_clubs.each do |club| %>
    <%= link_to club.name, club%>
  <% end %>
  </p>
<% else %>
  <p>no beerclub memberships</p>
<% end %>

<% if @user.ratings.any? %>
  <p> Favorite beer: <%= @user.favorite_beer.name %> </p>
  <p> Favorite brewery: <%= @user.favorite_brewery.name %> </p>
  <p> Favorite style: <%= @user.favorite_style %> </p>

  <p> average rating <%= round @user.average_rating %></p>

  <h3>ratings</h3>

  <ul>
  <% @user.ratings.each do |r| %>
    <li>
      <%= r %>
      <% if @user == current_user %>
        <%= link_to 'delete', r, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
  </ul>

<% end %>

<%if current_user.admin %>
    <%if @user.blocked %>
        <%= link_to "reactivate account", toggle_blocked_user_path(@user.id), method: :post,data: {confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <%else%>
        <%= link_to "froze account", toggle_blocked_user_path(@user.id), method: :post,data: {confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <%end%>
<%end%>

<% if @user==current_user%>
  <%= link_to 'change password', edit_user_path(@user), class:'btn btn-primary'%> <br>
  <%= link_to 'destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
<% end %>